version: "3.8"
services:
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - "9003:80"
        environment: 
            apiUrl: localhost/api
    api:
        build: 
            context: ./API
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
        restart: always
        environment:
            - DBHOST=db
            - DBPORT=3306
            - DBUSER=ivertion
            - DBPASSWORD=1V3rT10n

        depends_on:
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db

    php:
        image: php:7.2-fpm
        volumes:
        - /var/www/docker-study.loc/recipe-03/php:/var/www/myapp
        - /var/www/docker-study.loc/recipe-03/docker/php.ini:/usr/local/etc/php/php.ini

    #DataBase Service
    db:
        #Pull the latest mysql image
        image: mariadb:lts-jammy
        #Map port 3306 on the mysql container to port 3306 in the host
        ports:
        - "3306:3306"
        #Specify where the persisted Data should be stored
        volumes:
        - db-volume:/var/lib/mysql
        # - "./init:/docker-entrypoint-initdb.d"
        restart: always
        #Specify Environment Variables for mysql
        environment: 
            MARIADB_ROOT_PASSWORD: 1V3rT10n
            MARIADB_USER: ivertion
            MARIADB_PASSWORD: 1V3rT10n
            MARIADB_DATABASE: ivertion


volumes:
    db-volume:



